### ISSUE TITLE
Lot's of vulnerabilities for image v1.0.2

### ISSUE THREAD

**Issue by jvilimek** [spotify/lighthouse-audit-service#65]
Dears,

we have just executed vulnerability scan over the lastest (v1.0.2) [lighthouse-audit-service](https://hub.docker.com/r/spotify/lighthouse-audit-service) and there are lot's of vulnerabilities there:
![image](https://user-images.githubusercontent.com/16001792/133645979-8147ea4f-7eb5-464d-a0f8-e3a75a50ebc5.png)

I believe lot's of them are caused by using node:12 base image. 

Could you please try to do the hardening of the image so it is not a threat to use it in our/other environments? E.g. see https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/

or what do you suggest?

**Comment by jvilimek** [comment]
@ODEit WDYT?

**Comment by jvilimek** [comment]
@kaimallea ?

**Comment by jvilimek** [comment]
@erikxiv ?

**Comment by kaimallea** [comment]
@jvilimek Hey Jan, thanks for raising this issue. We're tracking this internally and will update soon!
